#!/bin/bash

echo "Panel Installation Started"

# Step 1: installing Dependencies

sudo apt update

sudo apt install -y curl software-properties-common

curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -

sudo apt-get install nodejs -y

sudo apt install git -y

echo "Dependencies Installed"

# Step 2: Installing Files

mkdir -p panel5

cd panel5

git clone https://github.com/achul123/panel5.git

cd panel5

npm install

echo "Files Installed"

# Step 3: Running Seed

npm run seed

# Step 4: Creating User

npm run createUser

# Step 5: Installing Pm2

sudo npm install -g pm2
# Step 6: Starting Panel

pm2 start index.js

# Step 7: Clearing Screen

clear

echo "Made By ZyroSyth"
